CFLAGS = -Werror -Wall -Wno-unused

all: allegro openglallegro openglsdl sdl sdl2

allegro:
	g++ allegrohelloworld.cpp -o allegrohelloworld $(CFLAGS) \
	-lguichan_allegro -lguichan `allegro-config --libs --cflags`
	g++ allegrowidgets.cpp -o allegrowidgets  $(CFLAGS) \
	-lguichan_allegro -lguichan `allegro-config --libs --cflags`
	g++ allegroaction.cpp -o allegroaction $(CFLAGS) \
	-lguichan_allegro -lguichan `allegro-config --libs --cflags`

openglallegro:
	g++ openglallegrohelloworld.cpp -o openglallegrohelloworld  $(CFLAGS) \
	-lguichan_opengl -lguichan_allegro -lguichan -lGL -lGLU -lagl `allegro-config --libs --cflags`
	g++ openglallegrowidgets.cpp -o openglallegrowidgets  $(CFLAGS) \
	-lguichan_opengl -lguichan_allegro -lguichan -lGL -lGLU -lagl `allegro-config --libs --cflags`
	g++ openglallegrowidgets.cpp -o openglallegroaction  $(CFLAGS) \
	-lguichan_opengl -lguichan_allegro -lguichan -lGL -lGLU -lagl `allegro-config --libs --cflags`

openglsdl:
	g++ openglsdlhelloworld.cpp -o openglsdlhelloworld $(CFLAGS) \
	-lguichan_sdl -lguichan_opengl -lguichan -lSDL_image `sdl-config --libs --cflags` -lGL
	g++ openglsdlwidgets.cpp -o openglsdlwidgets $(CFLAGS) \
	-lguichan_sdl -lguichan_opengl -lguichan -lSDL_image `sdl-config --libs --cflags` -lGL
	g++ openglsdlaction.cpp -o openglsdlaction $(CFLAGS) \
	-lguichan_sdl -lguichan_opengl -lguichan -lSDL_image `sdl-config --libs --cflags` -lGL

sdl:
	g++ sdlhelloworld.cpp -o sdlhelloworld $(CFLAGS) \
	-lguichan_sdl -lguichan -lSDL_image `sdl-config --libs --cflags`
	g++ sdlwidgets.cpp -o sdlwidgets $(CFLAGS) \
	-lguichan_sdl -lguichan -lSDL_image `sdl-config --libs --cflags`
	g++ sdlaction.cpp -o sdlaction $(CFLAGS) \
	-lguichan_sdl -lguichan -lSDL_image `sdl-config --libs --cflags`

sdl2:
	g++ sdl2helloworld.cpp -o sdl2helloworld $(CFLAGS) \
	-lguichan_sdl2 -lguichan -lSDL2_image `sdl2-config --libs --cflags`
	g++ sdl2widgets.cpp -o sdl2widgets $(CFLAGS) \
	-lguichan_sdl2 -lguichan -lSDL2_image `sdl2-config --libs --cflags`

clean:
	rm -f allegroaction allegrohelloworld allegrowidgets
	rm -f openglallegroaction openglallegrohelloworld openglallegrowidgets
	rm -f openglsdlaction openglsdlhelloworld openglsdlwidgets
	rm -f sdlaction sdlhelloworld sdlwidgets
	rm -f sdl2helloworld sdl2widgets